services:
    db:
        image: mysql:8.0
        container_name: school_db
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - '3306:3307'
        volumes:
            - db_data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: school_app
        restart: unless-stopped
        ports:
            - '4000:4000'
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./:/app # mount code for dev hot‐reload
            - /app/node_modules # prevent overwriting container’s modules
        command: node dist/app.js # for production you can remove volumes and use default CMD

volumes:
    db_data:
