services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sms-app
        restart: unless-stopped
        ports:
            - '${PORT:-3000}:3000'
        depends_on:
            - db
        environment:
            - NODE_ENV=${NODE_ENV:-development}
            - PORT=${PORT:-3000}
            - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
            - DB_HOST=db
            - DB_PORT=${DB_PORT:-3307}
            - DB_NAME=${DB_NAME:-school_management}
            - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
            - DATABASE_URI=mysql://root:${MYSQL_ROOT_PASSWORD:-rootpassword}@db:${DB_PORT:-3307}/${DB_NAME:-school_management}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
            - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_SECURE=${EMAIL_SECURE}
            - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
            - EMAIL_USER=${EMAIL_USER}
            - UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
        volumes:
            - ./:/app
            - /app/node_modules

    db:
        image: mysql:8.0
        container_name: sms-mysql
        restart: unless-stopped
        ports:
            - '${DB_PORT:-3307}:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
            - MYSQL_DATABASE=${DB_NAME:-school_management}
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
