// src/seeders/teacher.seeder.ts
import { Teacher } from '@/models/Teacher'
// import { Subject } from '@/models/Subject'

export const seedTeachers = async () => {
    try {
        await Teacher.bulkCreate(
            [
                {
                    firstName: 'Test',
                    lastName: 'Teacher',
                    email: 'teacher@example.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Male',
                    phoneNo: '1234567890',
                    address: 'Test Address',
                    cnic: '1234567891234',
                    highestQualification: 'Masters',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Test Contact',
                    emergencyContactNumber: '0987654321',
                    subjectId: 1, // Assuming 1 is the ID for Maths
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
                {
                    firstName: 'Jane',
                    lastName: 'Doe',
                    email: 'jane.doe@example.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Female',
                    phoneNo: '1234567891',
                    address: 'Test Address 2',
                    cnic: '1234567891235',
                    highestQualification: 'Bachelors',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Jane Contact',
                    emergencyContactNumber: '0987654322',
                    subjectId: 2, // Assuming 2 is the ID for English
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
                {
                    firstName: 'Jane',
                    lastName: 'Doe',
                    email: 'jane.doe@gmail.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Female',
                    phoneNo: '1234567891',
                    address: 'Test Address 2',
                    cnic: '1234567891235',
                    highestQualification: 'Bachelors',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Jane Contact',
                    emergencyContactNumber: '0987654322',
                    subjectId: 3, // Assuming 2 is the ID for English
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
                {
                    firstName: 'M',
                    lastName: 'Yasseen',
                    email: 'yasseen@gmail.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Female',
                    phoneNo: '1234567891',
                    address: 'Test Address 2',
                    cnic: '1234567891235',
                    highestQualification: 'Bachelors',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Jane Contact',
                    emergencyContactNumber: '0987654322',
                    subjectId: 4, // Assuming 2 is the ID for English
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
                {
                    firstName: 'Abdul',
                    lastName: 'Rehman',
                    email: 'abdulRehman@gmail.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Female',
                    phoneNo: '1234567891',
                    address: 'Test Address 2',
                    cnic: '1234567891235',
                    highestQualification: 'Bachelors',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Jane Contact',
                    emergencyContactNumber: '0987654322',
                    subjectId: 5, // Assuming 2 is the ID for English
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
                {
                    firstName: 'Anjum',
                    lastName: 'Yasseen',
                    email: 'yasseenanjum@gmail.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Female',
                    phoneNo: '1234567891',
                    address: 'Test Address 2',
                    cnic: '1234567891235',
                    highestQualification: 'Bachelors',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Jane Contact',
                    emergencyContactNumber: '0987654322',
                    subjectId: 6, // Assuming 2 is the ID for English
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
                {
                    firstName: 'Abdul',
                    lastName: 'Rehman',
                    email: 'abdulRehman@gmail.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Female',
                    phoneNo: '1234567891',
                    address: 'Test Address 2',
                    cnic: '1234567891235',
                    highestQualification: 'Bachelors',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Jane Contact',
                    emergencyContactNumber: '0987654322',
                    subjectId: 5, // Assuming 2 is the ID for English
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
                {
                    firstName: 'Abdul',
                    lastName: 'Rehman',
                    email: 'abdul@gmail.com',
                    password: 'password',
                    dateOfBirth: new Date('2000-01-01'),
                    gender: 'Female',
                    phoneNo: '1234567891',
                    address: 'Test Address 2',
                    cnic: '1234567891235',
                    highestQualification: 'Bachelors',
                    joiningDate: new Date('2025-01-30'),
                    emergencyContactName: 'Jane Contact',
                    emergencyContactNumber: '0987654322',
                    subjectId: 7, // Assuming 2 is the ID for English
                    isVerified: true,
                    entityType: 'TEACHER',
                    role: 'TEACHER',
                },
            ],
            { ignoreDuplicates: true },
        ) // Ignore duplicates on subsequent seeding
        console.log('Teachers seeded successfully')
    } catch (error) {
        console.error('Error seeding teachers:', error)
    }
}
